### ISSUE TITLE
MQTT Only

### ISSUE THREAD

**Issue by asknoone** [mhwlng/fiphwinfo#2]
Hi there,

I don't have a Logitech Flight panel but I would definitely like to use the MQTT functionality.

If I just create and configure the MQTT file will it work okay without a panel connected? Also, what sensors does it send over MQTT, the ones configured in the HWINFO.inc file presumably?

What frequency will the updates be sent via MQTT? Some of the sensor values will change every second or so I imagine so would be good to only send updates a maximum of every x seconds per sensor.

Thanks for your help!

(I think you should consider renaming your repo and adding some more specific text in the ReadMe because I think that a lot of the Home automation community, e.g. people who use Home Assistant would like to use this, but probably haven't come across it)

**Comment by mhwlng** [comment]
This software is meant specifically for the fip panel. 
I don't plan to make an MQTT only version.
You're welcome to fork the code and make your own version with the fip panel functionality taken out and just keep the MQTT stuff.
